server:
  port: 8080

spring:
  application:
    name: pr-client-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 600s
  data:
    redis:
      host: localhost
      port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0    # 100% in dev; reduce in prod (e.g., 0.1)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus, beans
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    git:
      mode: full
info:
  app:
    name: practica2
    version: 0.0.1
    description: Demo project for Spring Boot




feign:
  client:
    config:
      FOREST-SERVICE:
        connectTimeout: 2000
        readTimeout: 3000

resilience4j.retry:
  instances:
    paymentRetry:
      maxAttempts: 3
      waitDuration: 300ms
      retryExceptions:
        - feign.RetryableException
        - java.io.IOException




